# Generated by Django 2.2.1 on 2019-07-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jikbang',
            name='body',
            field=models.TextField(),
        ),
    ]
